### ISSUE TITLE
incoerenta nume functii

### ISSUE THREAD

**Issue by SilviuTM** [HoaraIonut/Programare-Orientata-pe-Obiecte-Proiect-1#1]
unele functii nu incep cu litera mare. cringe. cine te-a invatat programare?

**Comment by HoaraIonut** [comment]
Cine?

**Comment by SilviuTM** [comment]
cine teantrebat ahahahahahaha 🤣🤣🤣🤣🤣😳😳😳😳🤡🤡🗿🗿
